-- BIOMED guided learning state, exams and idempotent learning actions
create table if not exists public.biomed_learning_state (
  student_id uuid primary key references public.biomed_students(id) on delete cascade,
  current_module text not null default 'perceber',
  current_lesson text not null default 'perceber-1',
  completed_lessons jsonb not null default '[]'::jsonb,
  module_progress jsonb not null default '{}'::jsonb,
  exam_status jsonb not null default '{}'::jsonb,
  last_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint biomed_learning_state_module_check check (current_module = any(array['perceber','conduzir','processar','modular','aplicar'])),
  constraint biomed_learning_state_completed_array check (jsonb_typeof(completed_lessons)='array'),
  constraint biomed_learning_state_progress_object check (jsonb_typeof(module_progress)='object'),
  constraint biomed_learning_state_exam_object check (jsonb_typeof(exam_status)='object')
);

create table if not exists public.biomed_exam_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.biomed_students(id) on delete cascade,
  attempt_key text not null,
  module_id text not null,
  exam_type text not null default 'stage',
  score numeric(5,2) not null check (score between 0 and 100),
  pass_threshold numeric(5,2) not null default 70 check (pass_threshold between 1 and 100),
  passed boolean not null,
  answers jsonb not null default '[]'::jsonb,
  weaknesses jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(student_id, attempt_key),
  constraint biomed_exam_module_check check (module_id = any(array['perceber','conduzir','processar','modular','aplicar','cumulative'])),
  constraint biomed_exam_type_check check (exam_type = any(array['stage','cumulative'])),
  constraint biomed_exam_answers_array check (jsonb_typeof(answers)='array'),
  constraint biomed_exam_weaknesses_array check (jsonb_typeof(weaknesses)='array')
);

create index if not exists biomed_exam_attempts_student_created_idx
  on public.biomed_exam_attempts(student_id, created_at desc);

alter table public.biomed_learning_state enable row level security;
alter table public.biomed_exam_attempts enable row level security;

revoke all on public.biomed_learning_state from anon, authenticated;
revoke all on public.biomed_exam_attempts from anon, authenticated;

create or replace function public.biomed_learning_profile(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  sid uuid := public.biomed_student_id_from_token(p_token);
  s public.biomed_students%rowtype;
  l public.biomed_learning_state%rowtype;
  attempts jsonb;
begin
  if sid is null then raise exception 'Sessão inválida ou expirada'; end if;

  insert into public.biomed_learning_state(student_id)
  values(sid)
  on conflict(student_id) do nothing;

  select * into s from public.biomed_students where id=sid;
  select * into l from public.biomed_learning_state where student_id=sid;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
  into attempts
  from (
    select id, module_id as "moduleId", exam_type as "examType", score,
           pass_threshold as "passThreshold", passed, weaknesses, created_at as "createdAt"
    from public.biomed_exam_attempts
    where student_id=sid
    order by created_at desc
    limit 30
  ) x;

  return jsonb_build_object(
    'student', public.biomed_student_json(s),
    'learningState', jsonb_build_object(
      'currentModule', l.current_module,
      'currentLesson', l.current_lesson,
      'completedLessons', l.completed_lessons,
      'moduleProgress', l.module_progress,
      'examStatus', l.exam_status,
      'lastAction', l.last_action,
      'updatedAt', l.updated_at
    ),
    'examAttempts', attempts,
    'passThreshold', 70
  );
end;
$function$;

create or replace function public.biomed_learning_action(
  p_token text,
  p_event_key text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  sid uuid := public.biomed_student_id_from_token(p_token);
  l public.biomed_learning_state%rowtype;
  s public.biomed_students%rowtype;
  allowed text[] := array['lesson_started','lesson_completed','checkpoint','practice','exam_completed','tutor_action','tutor_answer','resume'];
  modules text[] := array['perceber','conduzir','processar','modular','aplicar'];
  module_id text := lower(left(coalesce(p_payload->>'moduleId',''),40));
  lesson_id text := left(coalesce(p_payload->>'lessonId',''),80);
  next_module text := lower(left(coalesce(p_payload->>'nextModule',''),40));
  next_lesson text := left(coalesce(p_payload->>'nextLesson',''),80);
  progress_value numeric;
  score_value numeric;
  threshold_value numeric;
  passed_value boolean;
  exam_type_value text;
  completed jsonb;
  progress jsonb;
  exams jsonb;
  prev jsonb;
  inserted_count integer := 0;
  stats_value jsonb;
  learning_score_value numeric;
  level_value text;
begin
  if sid is null then raise exception 'Sessão inválida ou expirada'; end if;
  if not (p_action = any(allowed)) then raise exception 'Ação de aprendizagem inválida'; end if;
  if coalesce(length(p_event_key),0) < 4 or length(p_event_key) > 120 then raise exception 'event_key inválida'; end if;

  insert into public.biomed_learning_state(student_id)
  values(sid)
  on conflict(student_id) do nothing;

  insert into public.biomed_events(student_id,event_key,event_type,topic,payload)
  values(sid,p_event_key,'learning_'||p_action,null,coalesce(p_payload,'{}'::jsonb))
  on conflict(student_id,event_key) do nothing;
  get diagnostics inserted_count = row_count;

  select * into l from public.biomed_learning_state where student_id=sid for update;

  if inserted_count = 0 then
    return public.biomed_learning_profile(p_token) || jsonb_build_object('duplicate',true);
  end if;

  if p_action in ('lesson_started','lesson_completed') then
    if not (module_id = any(modules)) then raise exception 'Módulo inválido'; end if;
    if lesson_id = '' then raise exception 'Aula inválida'; end if;
  end if;

  if p_action='lesson_started' then
    update public.biomed_learning_state
    set current_module=module_id,
        current_lesson=lesson_id,
        last_action=p_action,
        updated_at=now()
    where student_id=sid;

  elsif p_action='lesson_completed' then
    completed := coalesce(l.completed_lessons,'[]'::jsonb);
    if not exists(select 1 from jsonb_array_elements_text(completed) x(value) where value=lesson_id) then
      completed := completed || to_jsonb(lesson_id);
    end if;

    progress := coalesce(l.module_progress,'{}'::jsonb);
    if p_payload ? 'moduleProgress' then
      progress_value := greatest(0,least(100,coalesce((p_payload->>'moduleProgress')::numeric,0)));
      progress := jsonb_set(progress,array[module_id],to_jsonb(progress_value),true);
    end if;

    if not (next_module = any(modules)) then next_module := module_id; end if;
    if next_lesson = '' then next_lesson := lesson_id; end if;

    update public.biomed_learning_state
    set completed_lessons=completed,
        module_progress=progress,
        current_module=next_module,
        current_lesson=next_lesson,
        last_action=p_action,
        updated_at=now()
    where student_id=sid;

  elsif p_action='exam_completed' then
    if module_id='' then module_id:='cumulative'; end if;
    if not (module_id = any(array['perceber','conduzir','processar','modular','aplicar','cumulative'])) then
      raise exception 'Módulo de prova inválido';
    end if;
    score_value := greatest(0,least(100,coalesce((p_payload->>'score')::numeric,0)));
    threshold_value := greatest(1,least(100,coalesce((p_payload->>'passThreshold')::numeric,70)));
    passed_value := score_value >= threshold_value;
    exam_type_value := case when coalesce(p_payload->>'examType','stage')='cumulative' then 'cumulative' else 'stage' end;

    insert into public.biomed_exam_attempts(
      student_id,attempt_key,module_id,exam_type,score,pass_threshold,passed,answers,weaknesses
    ) values (
      sid,p_event_key,module_id,exam_type_value,score_value,threshold_value,passed_value,
      case when jsonb_typeof(coalesce(p_payload->'answers','[]'::jsonb))='array' then coalesce(p_payload->'answers','[]'::jsonb) else '[]'::jsonb end,
      case when jsonb_typeof(coalesce(p_payload->'weaknesses','[]'::jsonb))='array' then coalesce(p_payload->'weaknesses','[]'::jsonb) else '[]'::jsonb end
    ) on conflict(student_id,attempt_key) do nothing;

    exams := coalesce(l.exam_status,'{}'::jsonb);
    prev := coalesce(exams->module_id,'{}'::jsonb);
    exams := jsonb_set(
      exams,array[module_id],
      jsonb_build_object(
        'latest',score_value,
        'best',greatest(score_value,coalesce((prev->>'best')::numeric,0)),
        'passed',passed_value or coalesce((prev->>'passed')::boolean,false),
        'attempts',coalesce((prev->>'attempts')::integer,0)+1,
        'updatedAt',now()
      ),true
    );

    select * into s from public.biomed_students where id=sid for update;
    stats_value := jsonb_build_object(
      'mastery','{}'::jsonb,
      'content_completed','[]'::jsonb,
      'diagnostic_done',false,
      'exam_scores','[]'::jsonb,
      'simulation_scores','[]'::jsonb,
      'case_scores','[]'::jsonb,
      'open_answer_scores','[]'::jsonb,
      'retention_scores','[]'::jsonb,
      'active_days','[]'::jsonb,
      'questions_answered',0,
      'questions_correct',0,
      'tutor_turns',0
    ) || coalesce(s.stats,'{}'::jsonb);
    stats_value := public.biomed_append_score(stats_value,'exam_scores',score_value);
    learning_score_value := public.biomed_compute_score(stats_value);
    level_value := public.biomed_determine_level(stats_value,learning_score_value);

    update public.biomed_students
    set stats=stats_value,
        learning_score=learning_score_value,
        level=level_value,
        xp=greatest(0,s.xp + case when passed_value then 120 else 40 end),
        last_seen_at=now()
    where id=sid;

    update public.biomed_learning_state
    set exam_status=exams,last_action=p_action,updated_at=now()
    where student_id=sid;

  else
    update public.biomed_learning_state
    set last_action=p_action,updated_at=now()
    where student_id=sid;
  end if;

  return public.biomed_learning_profile(p_token) || jsonb_build_object('duplicate',false);
end;
$function$;

revoke all on function public.biomed_learning_profile(text) from public;
revoke all on function public.biomed_learning_action(text,text,text,jsonb) from public;
grant execute on function public.biomed_learning_profile(text) to anon, authenticated;
grant execute on function public.biomed_learning_action(text,text,text,jsonb) to anon, authenticated;
